name: 🐛 Bug
description: File a bug/issue
title: "[BUG] <title>"
labels: ["bug"]
body:
- type: checkboxes
  attributes:
    label: 🚀 Are you trying to Self Host the bot?
    description: Please state if you are encountering the bug when using the official bot [Crafty] or when running a cloned/self Hosted version of it.
    options:
    - label: I am using the official bot
      required: false
- type: textarea
  attributes:
    label: 🤔 Current Behavior
    description: A concise description of what you're experiencing.
    placeholder: |
      The bot is...
  validations:
    required: true
- type: textarea
  attributes:
    label: ✅ Expected Behavior
    description: A concise description of what you expected to happen.
    placeholder: |
      I expected...
  validations:
    required: false
- type: textarea
  attributes:
    label: 📝 Steps To Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. Run this command...
      2. Open up this...
      3. Recieve '...'
      4. See error...
  validations:
    required: true
- type: textarea
  attributes:
    label: ℹ️ Anything else?
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
