name: Bug report
description: Report a bug in the official bot or a cloned version

inputs:
  bot_version:
    description: 'Are you using the official bot or a cloned version?'
    type: checkboxes
    options:
      official:
        description: 'Official bot'
      cloned:
        description: 'Cloned version'

  cloned_description:
    description: 'Please provide all the steps you followed since you installed the bot.'
    type: textarea
    when: bot_version == 'cloned'

  official_description:
    description: 'Please describe what you did.'
    type: textarea
    when: bot_version == 'official'



