name: Bug report
about: Report a bug in the official bot or a cloned version

---

# Are you using the official bot or a cloned version?
description: |
  Please select the appropriate option below and fill in the corresponding details.

steps:
- name: Bot version
  description: Are you using the official bot or a cloned version?
  id: bot-version
  type: radio
  options:
    official:
      label: Official bot
      description: ''
    cloned:
      label: Cloned version
      description: ''

- name: Cloned version description
  description: Please provide all the steps you followed since you installed the bot.
  id: cloned-description
  type: textarea
  when: steps.bot-version == 'cloned'

- name: Official version description
  description: Please describe what you did.
  id: official-description
  type: textarea
  when: steps.bot-version == 'official'



