name: Bot

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    env:
      TOKEN: ${{ secrets.token }}
      clientID: ${{ secrets.clientID }}
      guildID: ${{ secrets.guildID }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install node.js v16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: npm install
        run: npm install
      - name: run
        run: node index.js
