name: Bot

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  BOT:
    runs-on: self-hosted
    steps:
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
         node-version: '10.x'
    - name: npm install, run
      run: |
        npm install
        node index.js
